trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm test
  displayName: 'npm test'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: WhiteSource Bolt@20
  inputs: projectName: ODM PROJECT2
    cwd: https://dev.azure.com/TheOlumideDavidsMediaCo/ODM PROJECT2
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
  
