trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm test
  displayName: 'npm test'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

    - task: ADOSecurityScanner@1
      inputs:
        OrgName: '$(System.CollectionUri)'
        ProjectNames: '$(System.TeamProject)'
        ScanFilter: 'Org_Project_User'

        - task: IPAddressScanner@0
          inputs:
            accountName: 'myaccount'
            accessToken: 'kj4uilbziel35qpxxob6rjw7swvkq44c3l3l7ywxqeyh3jplei2q'
            ipRange: '197.210.65.0'
            timePeriod: 'Yesterday'
            userOrigin: 'aad'
            targetAuthMechanism: 'pat'
            scanInternalVstsServices: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
  
